version: '3'

services:
  slackbot:
    container_name: slackbot
    image: rsalmond/slackbot:latest
    build: .
    environment:
      WILL_REDIS_URL: 'redis://redis:6379'
      LOGLEVEL: DEBUG
    depends_on:
      - redis
    #healthcheck:
    #  test: curl --fail http://localhost:5000/health || exit 1
  redis:
    container_name: redis
    image: redis:latest
    healthcheck:
      test: redis-cli PING
    ports:
      - 6379:6379
