apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "slackbot.fullname" . }}
  labels:
    app: {{ template "slackbot.name" . }}
    chart: {{ template "slackbot.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  WILL_LOGLEVEL: DEBUG
  WILL_K8S_NAME: {{ template "slackbot.fullname" . }}
  WILL_SLACK_DEFAULT_CHANNEL: general
  TZ: 'US/Pacific'
