apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "slackbot.fullname" . }}
  labels:
    app: {{ template "slackbot.name" . }}
    chart: {{ template "slackbot.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "slackbot.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "slackbot.name" . }}
        release: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ template "slackbot.fullname" . }}
      containers:
        - name: {{ .Chart.Name }}-redis
          image: redis
          imagePullPolicy: IfNotPresent
        - name: {{ .Chart.Name }}
          command: ["python3"]
          args: ["/slackbot/run_will.py"]
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
          - configMapRef:
              name: {{ template "slackbot.fullname" . }}
          env:
            - name: WILL_SLACK_API_TOKEN
              valueFrom:
                secretKeyRef:
                  key: slack_api_token
                  name: slackbot
            - name: WILL_SLACKBOT_API_KEY
              valueFrom:
                secretKeyRef:
                  key: slackbot_api_key
                  name: slackbot
            - name: WILL_ORBNEXT_DEVICE_ID
              valueFrom:
                secretKeyRef:
                  key: orbnext_device_id
                  name: slackbot
            - name: WILL_DOCKER_USERNAME
              valueFrom:
                secretKeyRef:
                  key: docker_username
                  name: slackbot
            - name: WILL_DOCKER_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: docker_password
                  name: slackbot
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          lifecycle:
            preStop:
              exec:
                # SIGINT stops all of Will's subprocesses
                command: ["/bin/kill", "-SIGINT", "1"]
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
